import faker from 'faker';

const getAllData = () => {
  faker.locale = 'en_US';
  return {
    address: {
      city: faker.address.city(),
      state: faker.address.state(),
      zipCode: faker.address.zipCode(),
      country: faker.address.country(),
      stateAbbr: faker.address.stateAbbr(),
      streetName: faker.address.streetName(),
      countryCode: faker.address.countryCode(),
      streetAddress: faker.address.streetAddress(),
      secondaryAddress: faker.address.secondaryAddress(),
    },
    finance: {
      mask: faker.finance.mask(),
      amount: faker.finance.amount(),
      account: faker.finance.account(),
      accountName: faker.finance.accountName(),
      currencyCode: faker.finance.currencyCode(),
      currencyName: faker.finance.currencyName(),
      currencySymbol: faker.finance.currencySymbol(),
      transactionType: faker.finance.transactionType(),
    },
    commerce: {
      color: faker.commerce.color(),
      price: faker.commerce.price(),
      product: faker.commerce.product(),
      department: faker.commerce.department(),
      productName: faker.commerce.productName(),
      productMaterial: faker.commerce.productMaterial(),
      productAdjective: faker.commerce.productAdjective(),
    },
    company: {
      bs: faker.company.bs(),
      bsBuzz: faker.company.bsBuzz(),
      bsNoun: faker.company.bsNoun(),
      suffixes: faker.company.suffixes(),
      companyName: faker.company.companyName(),
      catchPhrase: faker.company.catchPhrase(),
      bsAdjective: faker.company.bsAdjective(),
      companySuffix: faker.company.companySuffix(),
      catchPhraseNoun: faker.company.catchPhraseNoun(),
      catchPhraseAdjective: faker.company.catchPhraseAdjective(),
      catchPhraseDescriptor: faker.company.catchPhraseDescriptor(),
    },
    date: {
      past: faker.date.past(),
      month: faker.date.month(),
      future: faker.date.future(),
      recent: faker.date.recent(),
      between: faker.date.between(),
      weekday: faker.date.weekday(),
    },
    hacker: {
      noun: faker.hacker.noun(),
      verb: faker.hacker.verb(),
      phrase: faker.hacker.phrase(),
      ingverb: faker.hacker.ingverb(),
      adjective: faker.hacker.adjective(),
      abbreviation: faker.hacker.abbreviation(),
    },
    helpers: {
      slugify: faker.helpers.slugify(),
      shuffle: faker.helpers.shuffle(),
      mustache: faker.helpers.mustache(),
      userCard: faker.helpers.userCard(),
      randomize: faker.helpers.randomize(),
      createCard: faker.helpers.createCard(),
      contextualCard: faker.helpers.contextualCard(),
      replaceSymbols: faker.helpers.replaceSymbols(),
      createTransaction: faker.helpers.createTransaction(),
      replaceSymbolWithNumber: faker.helpers.replaceSymbolWithNumber(),
    },
    image: {
      cats: faker.image.cats(),
      city: faker.image.city(),
      food: faker.image.food(),
      image: faker.image.image(),
      avatar: faker.image.avatar(),
      people: faker.image.people(),
      nature: faker.image.nature(),
      sports: faker.image.sports(),
      animals: faker.image.animals(),
      fashion: faker.image.fashion(),
      imageUrl: faker.image.imageUrl(),
      abstract: faker.image.abstract(),
      business: faker.image.business(),
      technics: faker.image.technics(),
      nightlife: faker.image.nightlife(),
      transport: faker.image.transport(),
    },
    internet: {
      ip: faker.internet.ip(),
      url: faker.internet.url(),
      mac: faker.internet.mac(),
      email: faker.internet.email(),
      color: faker.internet.color(),
      avatar: faker.internet.avatar(),
      userName: faker.internet.userName(),
      protocol: faker.internet.protocol(),
      password: faker.internet.password(),
      userAgent: faker.internet.userAgent(),
      domainName: faker.internet.domainName(),
      domainWord: faker.internet.domainWord(),
      domainSuffix: faker.internet.domainSuffix(),
    },
    lorem: {
      words: faker.lorem.words(),
      sentence: faker.lorem.sentence(),
      sentences: faker.lorem.sentences(),
      paragraph: faker.lorem.paragraph(),
      paragraphs: faker.lorem.paragraphs(),
    },
    name: {
      title: faker.name.title(),
      prefix: faker.name.prefix(),
      suffix: faker.name.suffix(),
      jobArea: faker.name.jobArea(),
      jobType: faker.name.jobType(),
      lastName: faker.name.lastName(),
      findName: faker.name.findName(),
      jobTitle: faker.name.jobTitle(),
      firstName: faker.name.firstName(),
      jobDescriptor: faker.name.jobDescriptor(),
    },
    phone: {
      phoneNumber: faker.phone.phoneNumber(),
      phoneFormats: faker.phone.phoneFormats(),
      phoneNumberFormat: faker.phone.phoneNumberFormat(),
    },
    random: {
      uuid: faker.random.uuid(),
      number: faker.random.number(),
      boolean: faker.random.boolean(),
      arrayElement: faker.random.arrayElement(),
      objectElement: faker.random.objectElement(),
    },
  };
};

module.exports = {
  getAllData,
};
